spring.datasource.url = jdbc:postgresql://localhost:5432/start_up
spring.datasource.username = postgres
spring.datasource.password = 4415
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
server.port=8080
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
gemini.api.key=AIzaSyBA64UQEXCTMSZoM-EKGjIlfqusR-f7RDI

#spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username = postgres
#spring.datasource.password = akow8434
#spring.datasource.driver-class-name = org.postgresql.Driver
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update
#server.port=80
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB